"""Opt-in structural PDF pipeline components."""

from .model import BBox, DocumentModel, PageModel, PhysicalElement
from .physical import PhysicalExtractor
from .layout import (
    ClusterSummary,
    ColumnConfig,
    ColumnModel,
    DBSCANConfig,
    DocumentProfile,
    ElementLayout,
    GutterCandidate,
    GutterConfig,
    GutterEvidence,
    LayoutAnalysis,
    LayoutAnalyzer,
    LayoutAnalyzerConfig,
    PageLayout,
    ReadingOrder,
    ZoneConfig,
    ZoneDetection,
)
from .candidates import (
    Candidate,
    CandidateDetection,
    CandidateDetector,
    CandidateDetectorConfig,
    CandidateGraphAnalyzer,
    CandidateScoreWeights,
    ContextBlock,
    DocumentGraph,
    DocumentGraphBuilder,
    EdgeType,
    FEATURE_SCHEMA,
    FEATURE_SCHEMA_VERSION,
    FeatureSchemaV1,
    FeatureVector,
    GraphEdge,
    GraphNode,
    GraphConfig,
    ImageOwnership,
    LegacyEvidenceProvider,
    PageSegment,
    QuestionRegion,
    QuestionRegionBuilder,
    RegionConfig,
    StructuralAnalysis,
    StructuralAnalyzer,
    StructuralAnalyzerConfig,
    analyze_structure,
)
from .solver import (
    AnswerKeyEvidence,
    ConfidenceThresholds,
    ConfidenceWeights,
    ConstraintSolveResult,
    ConstraintSolver,
    ConstraintSolverConfig,
    ConstraintViolation,
    DocumentParseConfidence,
    RecoveryPass,
    SequenceSolution,
    SolverConfig,
    solve_constraints,
)
from .question_ast import (
    ASTNode,
    AST_SCHEMA_VERSION,
    AST_VERSION,
    ContextNode,
    ExamDocumentNode,
    FigureNode,
    OptionGroupNode,
    OptionNode,
    QuestionAST,
    QuestionASTBuilder,
    QuestionHeaderNode,
    QuestionNode,
    StatementNode,
    TableNode,
    build_question_ast,
)
from .renderer import render_legacy_document, render_legacy_question_dict

__all__ = [
    "BBox", "DocumentModel", "PageModel", "PhysicalElement", "PhysicalExtractor",
    "LayoutAnalyzer", "LayoutAnalyzerConfig", "GutterConfig", "ColumnConfig",
    "DBSCANConfig", "ZoneConfig", "DocumentProfile", "LayoutAnalysis",
    "PageLayout", "ColumnModel", "GutterCandidate", "GutterEvidence",
    "ElementLayout", "ReadingOrder", "ClusterSummary", "ZoneDetection",
    "Candidate", "CandidateDetection", "CandidateDetector", "CandidateGraphAnalyzer",
    "CandidateDetectorConfig", "CandidateScoreWeights", "LegacyEvidenceProvider",
    "FEATURE_SCHEMA", "FEATURE_SCHEMA_VERSION", "FeatureSchemaV1", "FeatureVector",
    "StructuralAnalyzer", "StructuralAnalyzerConfig", "GraphConfig", "RegionConfig",
    "DocumentGraph", "DocumentGraphBuilder", "EdgeType", "GraphEdge", "GraphNode",
    "QuestionRegionBuilder", "StructuralAnalysis", "ContextBlock", "ImageOwnership",
    "PageSegment", "QuestionRegion", "analyze_structure",
    "SolverConfig", "ConstraintSolverConfig", "ConfidenceWeights",
    "ConfidenceThresholds", "ConstraintSolver", "ConstraintSolveResult",
    "SequenceSolution", "ConstraintViolation", "RecoveryPass", "AnswerKeyEvidence",
    "DocumentParseConfidence", "solve_constraints",
    "AST_SCHEMA_VERSION", "AST_VERSION", "ASTNode", "ContextNode", "ExamDocumentNode",
    "FigureNode", "OptionGroupNode", "OptionNode", "QuestionAST", "QuestionASTBuilder",
    "QuestionHeaderNode", "QuestionNode", "StatementNode", "TableNode", "build_question_ast",
    "render_legacy_document", "render_legacy_question_dict",
]
