-- Concurse.io - recriação completa do schema da aplicação
-- Alvo: PostgreSQL 14+ (incluindo PostgreSQL 16/Supabase)
--
-- ATENÇÃO: este arquivo é destrutivo. Ele remove todos os dados das tabelas
-- abaixo antes de recriá-las. Execute conectado ao banco correto.
--
-- O script remove apenas objetos pertencentes à aplicação. Não remova o
-- schema public inteiro em instalações Supabase, pois ele pode conter
-- extensões, funções ou tabelas que não pertencem ao Concurse.io.

BEGIN;

-- Remoção em ordem inversa das dependências.
DROP TABLE IF EXISTS public.user_exams CASCADE;
DROP TABLE IF EXISTS public.generated_exam_sessions CASCADE;
DROP TABLE IF EXISTS public.exam_sources CASCADE;
DROP TABLE IF EXISTS public.answer_key_match_audits CASCADE;
DROP TABLE IF EXISTS public.exam_attempts CASCADE;
DROP TABLE IF EXISTS public.questions CASCADE;
DROP TABLE IF EXISTS public.exams CASCADE;
DROP TABLE IF EXISTS public.exam_catalog CASCADE;
DROP TABLE IF EXISTS public.folders CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- Usuários. google_id armazena o hash/pseudônimo do subject do Google;
-- os dados pessoais em claro não devem ser gravados pela aplicação.
CREATE TABLE public.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    name VARCHAR(200),
    picture VARCHAR(500),
    email_encrypted TEXT,
    name_encrypted TEXT,
    picture_encrypted TEXT
);

-- Pastas particulares ou legadas de provas.
CREATE TABLE public.folders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    user_id INTEGER,
    CONSTRAINT folders_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id)
);

-- Prova canônica e seu estado de ingestão/gabarito.
CREATE TABLE public.exams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    status VARCHAR(20) DEFAULT 'Pendente',
    folder_id INTEGER,
    user_id INTEGER,
    source_url VARCHAR(500),
    gabarito_url VARCHAR(500),
    has_official_answers INTEGER DEFAULT 0,
    answer_key_source VARCHAR(50) DEFAULT 'none',
    doc_type VARCHAR(50) DEFAULT 'caderno_questoes',
    gabarito_coverage DOUBLE PRECISION DEFAULT 0.0,
    gabarito_text TEXT,
    match_score INTEGER DEFAULT 0,
    progress INTEGER DEFAULT 0,
    progress_message VARCHAR(300) DEFAULT 'Pendente',
    error_type VARCHAR(50),
    CONSTRAINT exams_folder_id_fkey
        FOREIGN KEY (folder_id) REFERENCES public.folders (id),
    CONSTRAINT exams_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id)
);

-- Questões extraídas. question_index é a posição canônica da cadeia,
-- separada do rótulo textual numero_questao.
CREATE TABLE public.questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id INTEGER,
    statement TEXT NOT NULL,
    options TEXT,
    correct_answer VARCHAR(10) NOT NULL,
    subject VARCHAR(100) DEFAULT 'Geral',
    images TEXT,
    numero_questao VARCHAR(50),
    question_index INTEGER,
    latex_support INTEGER DEFAULT 0,
    difficulty_level VARCHAR(20) DEFAULT 'Média',
    CONSTRAINT questions_exam_id_fkey
        FOREIGN KEY (exam_id) REFERENCES public.exams (id)
);

-- Tentativas de resolução de uma prova.
CREATE TABLE public.exam_attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id INTEGER,
    score INTEGER DEFAULT 0,
    total INTEGER DEFAULT 0,
    percentage DOUBLE PRECISION DEFAULT 0.0,
    elapsed_seconds INTEGER DEFAULT 0,
    answers_json TEXT,
    created_at VARCHAR(30),
    user_id INTEGER,
    CONSTRAINT exam_attempts_exam_id_fkey
        FOREIGN KEY (exam_id) REFERENCES public.exams (id),
    CONSTRAINT exam_attempts_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id)
);

-- Histórico das decisões automáticas de vinculação de gabarito.
CREATE TABLE public.answer_key_match_audits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id INTEGER NOT NULL,
    accepted INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'not_found',
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    answer_source VARCHAR(50) NOT NULL DEFAULT 'none',
    method VARCHAR(50) NOT NULL DEFAULT 'none',
    candidate_page INTEGER,
    decision_json TEXT NOT NULL DEFAULT '{}',
    created_at VARCHAR(30) NOT NULL,
    CONSTRAINT answer_key_match_audits_exam_id_fkey
        FOREIGN KEY (exam_id) REFERENCES public.exams (id)
);

-- Biblioteca do usuário: uma mesma prova canônica pode ser compartilhada
-- entre usuários sem duplicar suas questões e seus artefatos.
CREATE TABLE public.user_exams (
    user_id INTEGER NOT NULL,
    exam_id INTEGER NOT NULL,
    created_at VARCHAR(30) NOT NULL,
    PRIMARY KEY (user_id, exam_id),
    CONSTRAINT user_exams_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id),
    CONSTRAINT user_exams_exam_id_fkey
        FOREIGN KEY (exam_id) REFERENCES public.exams (id)
);

-- URLs alternativas que identificam a mesma prova canônica.
CREATE TABLE public.exam_sources (
    source_key VARCHAR(64) PRIMARY KEY,
    source_url VARCHAR(500) NOT NULL,
    exam_id INTEGER NOT NULL,
    created_at VARCHAR(30) NOT NULL,
    CONSTRAINT exam_sources_exam_id_fkey
        FOREIGN KEY (exam_id) REFERENCES public.exams (id)
);

-- Referência persistente das questões originais de um simulado gerado.
CREATE TABLE public.generated_exam_sessions (
    exam_id INTEGER PRIMARY KEY,
    kind VARCHAR(50) NOT NULL,
    question_ids_json TEXT NOT NULL DEFAULT '[]',
    created_at VARCHAR(30) NOT NULL,
    CONSTRAINT generated_exam_sessions_exam_id_fkey
        FOREIGN KEY (exam_id) REFERENCES public.exams (id)
);

-- Catálogo usado na busca de fontes externas antes da ingestão.
CREATE TABLE public.exam_catalog (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_key VARCHAR(100),
    title VARCHAR(300) NOT NULL,
    source_url VARCHAR(500) NOT NULL,
    gabarito_url VARCHAR(500),
    match_score INTEGER DEFAULT 0,
    source VARCHAR(50) DEFAULT 'web',
    created_at VARCHAR(30)
);

-- Índices declarados pelo modelo SQLAlchemy (index=True/unique=True).
CREATE INDEX ix_folders_user_id
    ON public.folders (user_id);

CREATE INDEX ix_exams_status
    ON public.exams (status);
CREATE INDEX ix_exams_folder_id
    ON public.exams (folder_id);
CREATE INDEX ix_exams_user_id
    ON public.exams (user_id);
CREATE INDEX ix_exams_source_url
    ON public.exams (source_url);

CREATE INDEX ix_questions_exam_id
    ON public.questions (exam_id);
CREATE INDEX ix_questions_subject
    ON public.questions (subject);
CREATE INDEX ix_questions_question_index
    ON public.questions (question_index);

CREATE INDEX ix_exam_attempts_exam_id
    ON public.exam_attempts (exam_id);
CREATE INDEX ix_exam_attempts_user_id
    ON public.exam_attempts (user_id);

CREATE INDEX ix_answer_key_match_audits_exam_id
    ON public.answer_key_match_audits (exam_id);
CREATE INDEX ix_answer_key_match_audits_status
    ON public.answer_key_match_audits (status);

CREATE INDEX ix_exam_sources_exam_id
    ON public.exam_sources (exam_id);

CREATE INDEX ix_generated_exam_sessions_kind
    ON public.generated_exam_sessions (kind);

CREATE UNIQUE INDEX ix_users_google_id
    ON public.users (google_id);

CREATE INDEX ix_exam_catalog_query_key
    ON public.exam_catalog (query_key);
CREATE UNIQUE INDEX ix_exam_catalog_source_url
    ON public.exam_catalog (source_url);

COMMIT;
